---
title: "Regression Models - Course Project"
output: html_document
fontsize: 10pt
---
1)Use the FONT HTML tag in your markdown to change fontsize.
2)Use the stargazer package in R to make journal-quality, side-by-side regression tables. 
Works best in LaTeX, but even the markdown tables look nice.
3)Be sure to use the message=FALSE and warning=FALSE options in your R code chunks. You don't want to waste any space printing things like warnings and package-loading messages.

1)First page,  all text,  no code.  1/4 page exec summary and 1/4 page results, including interpretation of model. 1/2 page description of analytic approach and steps taken. 
2)Second page,  all code and output - mostly output
T3)hird page, just a big pairs plot,  color set to a certain factor variable of interest.
4)Fourth page, has 3 plots that explore the relationship of the chosen model's predictor variables to outcome. FYI,  number of plots is not necessaily related to number of predictors. 
5)Fifth page,  the four residual plots supported by lm object, and colored by a factor variable of interest. 

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
